# Generated by Django 4.2.11 on 2026-04-07 08:20

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Coordenada GPS (lng, lat)', srid=4326)),
                ('speed_kmh', models.FloatField(default=0.0, help_text='Velocidad en km/h')),
                ('heading', models.FloatField(default=0.0, help_text='Direccion en grados (0-360)')),
                ('accuracy_meters', models.FloatField(default=0.0, help_text='Precision del GPS en metros')),
                ('deviation_meters', models.FloatField(default=0.0, help_text='Distancia a la ruta fija')),
                ('is_deviated', models.BooleanField(default=False, help_text='True si supera la tolerancia')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('motorizado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_logs', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='services.service')),
            ],
            options={
                'verbose_name': 'Log de rastreo',
                'db_table': 'tracking_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('deviation', 'Desvio de ruta'), ('stop', 'Detencion prolongada'), ('speed', 'Velocidad excesiva'), ('manual', 'Reporte manual')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='services.service')),
                ('tracking_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.trackinglog')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackinglog',
            index=models.Index(fields=['service', 'timestamp'], name='tracking_lo_service_633d5d_idx'),
        ),
    ]
