# Generated by Django 4.2.11 on 2026-04-17 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('deviation', 'Desvio de ruta'), ('stop', 'Detencion prolongada'), ('speed', 'Velocidad excesiva'), ('manual', 'Reporte manual'), ('accident', 'Accidente'), ('breakdown', 'Averia del vehiculo'), ('traffic', 'Trafico / Congestion')], db_index=True, max_length=30),
        ),
    ]
