# Generated by Django 4.2.11 on 2026-04-28 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0002_incident_photo_incident_reported_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Respuesta del administrador al motorizado'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_resolved', to=settings.AUTH_USER_MODEL),
        ),
    ]
