# Generated by Django 4.2.11 on 2026-04-07 08:20

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(help_text='Trayectoria fija en formato LineString (GeoJSON)', srid=4326)),
                ('tolerance_meters', models.FloatField(default=100.0, help_text='Metros maximos que puede desviarse el motorizado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta',
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de aprobacion'), ('approved', 'Aprobado'), ('in_transit', 'En transito'), ('completed', 'Completado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('origin', django.contrib.gis.db.models.fields.PointField(help_text='Punto de recogida', srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(help_text='Punto de entrega', srid=4326)),
                ('notes', models.TextField(blank=True, help_text='Instrucciones adicionales')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_approved', to=settings.AUTH_USER_MODEL)),
                ('assigned_motorizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_assigned', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_requested', to=settings.AUTH_USER_MODEL)),
                ('route', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.route')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/')),
                ('file_url', models.URLField(blank=True, help_text='URL en S3 (produccion)')),
                ('doc_type', models.CharField(choices=[('delivery_note', 'Guia de remision'), ('invoice', 'Factura'), ('receipt', 'Recibo de conformidad'), ('other', 'Otro')], default='other', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='services.service')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
