# Generated by Django 4.2.11 on 2026-04-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='number',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Numero correlativo auto-asignado al crear el servicio', null=True, unique=True),
        ),
    ]
