# Generated by Django 4.2.11 on 2026-04-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='recipient_address',
            field=models.CharField(blank=True, help_text='Direccion del destinatario', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Nombre del destinatario', max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='Telefono del destinatario', max_length=20),
        ),
    ]
