# Generated by Django 4.2.11 on 2026-04-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='Direccion del usuario', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='avatars/'),
        ),
    ]
